[package]
name = "vine-node-core-av-store"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
kvdb = "0.13.0"
thiserror = "1.0.31"
gum = { package = "tracing-gum", path = "../../gum" }
bitvec = "1.0.0"

parity-scale-codec = { version = "3.1.5", features = ["derive"] }
erasure = { package = "vine-erasure-coding", path = "../../../erasure-coding" }
vine-node-subsystem = {path = "../../subsystem" }
vine-node-subsystem-util = { path = "../../subsystem-util" }
vine-overseer = { path = "../../overseer" }
vine-primitives = { path = "../../../primitives" }
vine-node-primitives = { path = "../../primitives" }

[dev-dependencies]
log = "0.4.17"
env_logger = "0.9.0"
assert_matches = "1.4.0"
kvdb-memorydb = "0.13.0"

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
vine-node-subsystem-util = { path = "../../subsystem-util" }
vine-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
parking_lot = "0.12.0"
test-helpers = { package = "vine-primitives-test-helpers", path = "../../../primitives/test-helpers" }
